name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Trigger Nightly Release
        run: make next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
