name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=release_version::${GITHUB_REF#refs/tags/}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - name: Delete Current Nightly Release
        if: "contains(github.ref, 'v0.0.0')"
        uses: larryjoelane/delete-release-action@v1.0.24
        with:
          release-name: weather-nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Nightly Release
        if: "contains(github.ref, 'v0.0.0')"
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist -f .goreleaser.nightly.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Release
        if: "!contains(github.ref, 'v0.0.0')"
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
